
openapi: 3.0.1
info:
  title: iig/rdg/shipment
  description: Import from "func-rpic-iig-rdg-requesthandler-dv-weu" Function App
  version: v1
servers:
  - url: https://apim-rpic-iig-dev.azure-api.net/rdg/shipment/v1
paths:
  /handlerequest:
    post:
      summary: Shipment
      operationId: post-handlerequest
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
